---
- name: configurar website
  tasks:
   - name: testando o index
     command:  "test -f /var/www/html/index.html"
     register: result
     ignore_errors: yes

   - name: adicionando site
     shell: echo '<h1> INFRAESTRUTURA AGIL COM DEVOPS</h1>' > /var/www/html/index.html
     when: result.rc == 0   
